### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by janelu9** [doccano/doccano-client#114]
HTTPConnectionPool(host='127.0.0.1', port=8000): Max retries exceeded with url: /v1/auth/login/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f4c07cb8280>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Hironsan** [comment]
Could you please paste code?

**Comment by david-engelmann** [comment]
should look something like.

```
base_url = 'http....'
username = 'blah'
password = 'b1ah'

client = DoccanoClient(
                base_url=base_url,
                verify=None)

client.login(username=username, password=password)
...
```
If you are still having issues, can you write the version of doccano-client you are using?
