### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

### ISSUE THREAD

**Issue by zic13** [doccano/doccano-client#118]
![Screenshot (158)](https://user-images.githubusercontent.com/116626468/197705363-a87ec346-724c-466b-ab7e-65137ef3318b.png)

Issue is like this ,unable to login to doccano ,its not logging in please help to resolve this issue.

```bash
 File "/home/finq/review/adam-1/adam/doccano/doccano_api/doccano_api.py", line 34, in __init__
    self.client.login(username,password)
  File "/home/finq/miniconda3/envs/adam/lib/python3.10/site-packages/doccano_client/client.py", line 116, in login
    self._base_repository.login(username, password)
  File "/home/finq/miniconda3/envs/adam/lib/python3.10/site-packages/doccano_client/repositories/base.py", line 93, in login
    verbose_raise_for_status(response)
  File "/home/finq/miniconda3/envs/adam/lib/python3.10/site-packages/doccano_client/repositories/base.py", line 34, in verbose_raise_for_status
    raise DoccanoAPIError(err.response)
  File "/home/finq/miniconda3/envs/adam/lib/python3.10/site-packages/doccano_client/repositories/base.py", line 16, in __init__
    super().__init__(str(response.json()), response=response)
  File "/home/finq/miniconda3/envs/adam/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 1)
```

*   Operating System: windows 11
*   Python Version: 3.10
*   Package Version: doccano 1.7.0 client version:-1.2.2

**Comment by Hironsan** [comment]
Please paste your code(`DoccanoClient`'s instantiation part).

**Comment by zic13** [comment]
```
class DoccanoAPI(DoccanoClient):
    def __init__(self):
        set_config_vars(self, ['doccano'])
        credentials = json_load(open(os.environ.get('adam_credentials')).read())
        if check_if_front_end(credentials):
            credentials = credentials['doccano']
        username = credentials['doccano']['username']
        password = credentials['doccano']['password']
        self.client=DoccanoClient(self.url)
        self.client.login(username,password)
        self.labels = get_labels()
```

Thanks fro the response @Hironsan . We are instantiating doccano client with the url, still facing the same issue.  Your response will be much helpful.

**Comment by Hironsan** [comment]
Is there any trailing slash(e.g. `http://127.0.0.1:8000/`)?

**Comment by zic13** [comment]
Yes I removed it and tried but got this issue.     
raise DoccanoAPIError(err.response)
doccano_client.repositories.base.DoccanoAPIError: {'non_field_errors': ['Unable to log in with provided credentials.']}

**Comment by Hironsan** [comment]
This means username or password is wrong. Please check it.

**Comment by zic13** [comment]
I am reading credentials from json file and passing to login function.Its giving me this issue.
 raise FailedToConnectDoccano
adam.common.exceptions.FailedToConnectDoccano: Could not connect to Doccano, make sure Doccano is running and check your credentials and permissions

**Comment by zic13** [comment]
![Uploading Screenshot (159).png…]()

**Comment by zic13** [comment]
![Screenshot (160)](https://user-images.githubusercontent.com/116626468/197724280-910b5a14-811e-48ed-ad36-59f0e026fc32.png)

**Comment by zic13** [comment]
I fixed login and I can login now . But theres is another issue raised due to user_repositories.

 File "/home/finq/miniconda3/envs/adam/lib/python3.10/site-packages/doccano_client/client.py", line 209, in get_profile
    return self._user_repository.get_profile()
AttributeError: 'DoccanoAPI' object has no attribute '_user_repository'``

**Comment by Hironsan** [comment]
> AttributeError: 'DoccanoAPI' object has no attribute '_user_repository'

Because you are not using DoccanoClient directly. DoccanoClient has `_user_repository` but your DoccanoAPI class does not have it.

**Comment by zic13** [comment]
get_profile() is not returning as list of users as of previous get_user_list() . So how it achieved to get all the users in doccano

**Comment by zic13** [comment]
File "/home/finq/miniconda3/envs/adam/lib/python3.10/site-packages/doccano_client/client.py", line 146, in relation_type
    service = LabelTypeService(self._relation_type_repository)
AttributeError: 'DoccanoAPI' object has no attribute '_relation_type_repository'

**Comment by zic13** [comment]
Stll it return the same sir. How can it be done

**Comment by Hironsan** [comment]
I recommend you use `DoccanoClient` directly.

```python
credentials = json_load(open(os.environ.get('adam_credentials')).read())
username = credentials['doccano']['username']
password = credentials['doccano']['password']
client = DoccanoClient(url)
client.login(username, password)
```
