### ISSUE TITLE
get_profile() is not returning as list of users as of previous get_user_list() . So how it achieved to get all the users in doccano. I need to get all the users I added to doccano ,but its showing only one user with id =1 as admin

### ISSUE THREAD

**Issue by zic13** [doccano/doccano-client#120]
get_profile() is not returning as list of users as of previous get_user_list() . So how it achieved to get all the users in doccano.
I need to get all the users I added to doccano ,but its showing only one user with id =1 as admin

**Comment by Hironsan** [comment]
https://doccano.github.io/doccano-client/usage/
