### ISSUE TITLE
project_labels = self.list_label_types(project_id,"relation")

### ISSUE THREAD

**Issue by zic13** [doccano/doccano-client#121]
File "/home/finq/miniconda3/envs/adam/lib/python3.10/site-packages/doccano_client/client.py", line 146, in relation_type
    service = LabelTypeService(self._relation_type_repository)
AttributeError: 'DoccanoAPI' object has no attribute '_relation_type_repository'

how to get list of lables in the project for new client version, How to pass Literal parameters. Thanks !

**Comment by zic13** [comment]
raise ValueError(f"Invalid type: {type}")
ValueError: Invalid type: typing.Literal['category', 'span', 'relation']

**Comment by Hironsan** [comment]
See https://github.com/doccano/doccano-client/issues/118#issuecomment-1290290867
