### ISSUE TITLE
  File "/home/finq/miniconda3/envs/adam/lib/python3.10/pathlib.py", line 1117, in open     return self._accessor.open(self, mode, buffering, encoding, errors, IsADirectoryError: [Errno 21] Is a directory: '/'

### ISSUE THREAD

**Issue by zic13** [doccano/doccano-client#128]
File "/home/finq/miniconda3/envs/adam/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
IsADirectoryError: [Errno 21] Is a directory: '/' 

Please can anyone help me to resolve this issue?

**Comment by zic13** [comment]
its happening is upload() function of new client version

**Comment by zic13** [comment]
how to declare this ? 
file_paths: List[str],

**Comment by david-engelmann** [comment]
file_paths = ["path/to/file.ext"]
