### ISSUE TITLE
    response = self.client.create_project(self, TypeError: DoccanoClient.create_project() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by zic13** [doccano/doccano-client#131]
response = self.client.create_project(self,
TypeError: DoccanoClient.create_project() got multiple values for argument 'name'

**Comment by zic13** [comment]
Please help to resolve this issue 
doccano version - 1.8.0
client-version - 1.2.6

**Comment by Hironsan** [comment]
The lack of information. Please paste your code correctly.

**Comment by david-engelmann** [comment]
`self.client.create_project(self,`

You shouldn't be passing self to this function
