### ISSUE TITLE
issue in uploading json file

### ISSUE THREAD

**Issue by zic13** [doccano/doccano-client#132]
```python
def upload_data(self,
                    project_id: int,
                    file_name: str,
                    file_folder: str = "./",
                    format: str = "JSONL"):
        logger.info(f'Uploading {file_name} to project {project_id}')
        self.client.upload(project_id=project_id,
                             file_paths=file_folder,
                             column_data=self.text_string,
                             column_label=self.label_string,
                             task=Task,
                             format=format)
```

this is te function and this is the issue:
  File "/home/finq/miniconda3/envs/adam/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
IsADirectoryError: [Errno 21] Is a directory: '/'

**Comment by Hironsan** [comment]
You need to pass a file list to `file_paths`:
- https://doccano.github.io/doccano-client/usage/#doccano_client.client.DoccanoClient.upload
