### ISSUE TITLE
 File "/home/finq/miniconda3/envs/adam/lib/python3.10/pathlib.py", line 1117, in open     return self._accessor.open(self, mode, buffering, encoding, errors, IsADirectoryError: [Errno 21] Is a directory: '/'

### ISSUE THREAD

**Issue by zic13** [doccano/doccano-client#133]
File "/home/finq/miniconda3/envs/adam/lib/python3.10/pathlib.py", line 1117, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
IsADirectoryError: [Errno 21] Is a directory: '/' 

List[str]=['/home/finq/review/doccano_update/adam/sandbox/input_data.jsonl']

this is what declared but still IsDirectory issue is raising

**Comment by Hironsan** [comment]
From your stack trace, you passed the directory path.
