### ISSUE TITLE
Cannot check the labels and how to get project ids as list in this new doccano client version?

### ISSUE THREAD

**Issue by zic13** [doccano/doccano-client#134]
File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Project
description
  ensure this value has at least 1 characters (type=value_error.any_str.min_length; limit_value=1)

**Comment by Hironsan** [comment]
The `description` field needs at least 1 character.
- https://doccano.github.io/doccano-client/usage/#doccano_client.client.DoccanoClient.create_project
