### ISSUE TITLE
add simple user through HTTP request

### ISSUE THREAD

**Issue by ghost** [doccano/doccano-client#4]
Hi, first of all nice work ! I use it a lot.

I don't manage to create (sign up) some new users by HTTP requests 
add_new_user(username, password, email)
Do you think it would be possible ?

For now I create a lot of admin users (by adding a lot of admin users in the doccano/tools/run.sh). But I don't like this way. 

Have a nice day !

**Comment by david-engelmann** [comment]
@Hironsan After some investigation, while some of the endpoints need to control user details are available with the current Doccano, the end to end process through an http request can't be completed without access to "auth/user/add/" endpoint. 

It appears the "admin" urls are set in the main doccano repo under ./backend/config/urls.py with the following lines

```
from django.contrib import admin
...
urlpatterns += [
          path("admin/", admin.site.urls), ...
```
It would seem that if this is a worthy initiative, a new user_details folder should be added to the backend directory and the urls and views etc. should be declared there and then referenced in the config/urls.py file. After that is accomplished, I can create a PR here for a version of the doccano-client that can make a user end to end through HTTP request

**Comment by Hironsan** [comment]
doccano uses [dj-rest-auth](https://github.com/iMerica/dj-rest-auth) for authentication and it supports user registration. So, I make a pull request to add a user creation endpoint(`/v1/users/creation`). We can use them to add users programmatically. The payload is as follows:

```bash
{
    "username": str,
    "password1": str,
    "password2": str
}
```

The `password2` is the confirmation purpose. So if we add the user creation method to doccano client, we only give `username` and `password` to it:

```python
client.create_user(username="", password="")
```
