### ISSUE TITLE
post_members

### ISSUE THREAD

**Issue by kovidiament** [doccano/doccano-client#43]
How to reproduce the behaviour
---------
pip install doccano-client ,
from doccano_api_client import DoccanoClient

Your Environment
---------

*   Operating System: windows 10
*   Python Version: 3.7
*   Package Version: 1.02

Problem is, the post_member function in github does work in the pip installation. I get,

line 45, in <module>
    members_add = doccano_client.post_members(project_id = project_info.id, usernames=userlist, roles=roleslist)

AttributeError: 'DoccanoClient' object has no attribute 'post_members'

I am also using PyCharm, and it does not recognize the function post_members.

Process finished with exit code 1

**Comment by kovidiament** [comment]
How do I add members to a project programatically?

**Comment by david-engelmann** [comment]
@kovidiament What version of doccano-client have you pip installed? I was able to get the function working by referencing a specific hash which had that function. In my requirements.txt file I had `doccano-client @ git+https://github.com/doccano/doccano-client.git@HASH`
