### ISSUE TITLE
Integrating Our Version of doccano-client?

### ISSUE THREAD

**Issue by ljades** [doccano/doccano-client#60]
Feature description
---------
Hey y'all,

First of all I just wanna say: Great job on this client!

Our company actually has been working on and maintaining a `doccano-client` as well around the time progress on this client started. It's currently internal, but we could easily open source it--hardly any of it is opinionated to our company's use cases.

The problem is, we don't have the hands at the moment to consistently maintain the package and keep it up to date with all the updates Doccano receives. It looks like this package has been able to, however, thanks to the open source visibility!

An idea: What are ya'll's thoughts on uniting the two? We can move our code to a fork of this repo, and create a major PR that integrates it right into this package if you like the results!

We believe our version of the client has a lot of features that this one can greatly benefit from:

1. Versioning lines up with Doccano release tags, so it is always clear when it will be compatible with which release of Doccano's API.
2. All interactions with the API are pythonic, rather than based on raw json. Example below.
3. VERY heavily unit tested.
4. Black, Isort, Flake8, Pydocstyle, Pylint, and Mypy compliant

```python
project_controllers = client.projects.all()

my_project_name_controller = next(controller for controller in project_controllers if controller.project.name == "My Project Name")

my_project_name_controller.labels.update([Label(...), Label(...)])

test_example = models.Example(text="This is an example text")
my_project_name_controller.examples.create(test_example)

```

Would you be interested in this style? There are a few more layers so may take a bit more code to maintain in some ways, but it should cut a lot of tech debt, making it easier to scale. If you're interested, we can port our code to a fork of this repo so you can take a look.

Thank you for your time!

**Comment by ljades** [comment]
@Hironsan Hey thank you so much for the quick response on this and the merge!

But now I'm curious for how you recommend we move forward with contributing to this. Can you answer these questions for me?

1. The primary client functionality is updated to compatibility with Doccano v1.6.x, correct? The new stuff we just merged is compatible with Doccano v.1.5.x. I set the new versioning in the `setup.py` to match our internal version, at 1.5.1. What do you think the version should be set to--should it match the new beta code or the main code interface? Or should we align them first, then set the version? Personally, I'm veering towards keeping it in the 1.5.x range until `doccano-client` is released at least once in that range (maybe set it to 1.5.5 at release to match the last stable Doccano release). Then we can switch to 1.6.x versioning here as well.
2. Should we add pytest to CI checking? My team can integrate that if it makes sense.
3. Once we have pytest verified as passing, when can we expect a release on this? If my team can start using this package once we confirm it's reasonably stable, we can stop using our internal package entirely and start contributing to this one directly instead.

Thanks!

**Comment by Hironsan** [comment]
Your welcome. Thank you for your great work!

1. > The primary client functionality is updated to compatibility with Doccano v1.6.x, correct?

Yes.

I think we can replace the current code with the beta code after supporting v1.6.x compatibility. The new code is great.
In this case, the version of `doccano-client` will be v2.0.0 (the current version is v1.0.3) because there are incompatible API changes.
- https://semver.org/

2. Yes!
3. Choices are:
  - v1.1.0(the current code and the beta code). In this case, I can release the package soon.
  - v2.0.0(only the beta code with v1.6.x compatibility)

**Comment by ljades** [comment]
>I think we can replace the current code with the beta code after supporting v1.6.x compatibility. The new code is great.

Oh wow that'd be a major stride and extremely humbling :)

2. Awesome! We'll get some cycles on this very soon. Probably in the next week or two--we're also gonna try to make the connection to the beta. Afterwards I think we'll be good to release this.
3. Re:the semver stuff from earlier too, yeah I hear what you're saying regarding fundamental API changes. The goal overall though with the versioning is that the Major and Minor version should have parity with Doccano release numbers, right?

What would you suggest would be the cleanest strategy to both follow good semver practices and also try to align with Doccano releases eventually too?

One idea would be to have them independent until Doccano is at 2.0.0, THEN bring this to 2.0.0 and leave only the beta code. That might be a while though.

Another option may be to have the next few versions of doccano-client bump minor version one-by-one (so 1.1.0, 1.2.0...1.6.0, until it matches Doccano's 1.6, then bring it back to Patch version bumping after).

Any other ideas?

**Comment by Hironsan** [comment]
I do not think it is necessary to align the doccano and doccano-client versions. This is because increasing the version of doccano does not necessarily cause changes in the API(e.g. patch version update by some bug fixes). In my opinion, the doccano and doccano-client versions should be independent. It is hard to align them.

I have checked several project versions:

- [TensorFlow](https://github.com/tensorflow/tensorflow) v2.8.0 vs [TFX](https://github.com/tensorflow/tfx) v1.7.1
- [spaCy](https://github.com/explosion/spaCy) v3.1.6 vs [spaCy Transformers](https://github.com/explosion/spacy-transformers) v1.1.5

> One idea would be to have them independent until Doccano is at 2.0.0, THEN bring this to 2.0.0 and leave only the beta code. That might be a while though.

Yes. You are right. It may take a long time.

Best

**Comment by Hironsan** [comment]
Writing the compatibility to the documentation and comment is good.
In another way, how about letting the user specify the version? For example:

```python
client = build_client(version="1.5", endpoint="http://")
client.login()
```

This is an analogy of [google-api-python-client](https://developers.google.com/docs/api/quickstart/python).

However, it might be troublesome to specify the version.

**Comment by ljades** [comment]
Yeah that'd probably be more challenging. Would involve supporting multiple versions of the Doccano API at once in possibly quite a lot of long-term permutations.

Anyway, thanks for the recommendations! We're gonna make one or two more PRs (the pytest CI inclusion, a bit more intuitive tie-in of the beta stuff into the existing documentation/module importing) and then I think we should be good for a release!

**Comment by Hironsan** [comment]
Thanks! I will make time and review it.
