### ISSUE TITLE
How to upload a label config file

### ISSUE THREAD

**Issue by TomLipshits5** [doccano/doccano-client#64]
How to reproduce the behaviour
---------
<!-- Before submitting an issue, make sure to check the docs and closed issues and FAQ to see if any of the solutions work for 
I have a json file that contains all the labels types I want to use, and while I import it successfully through the gui is seems like there is no way to is through the client

**Comment by david-engelmann** [comment]
https://github.com/doccano/doccano-client/pull/63

Depending on the project type you can use a particular group of endpoints. Look for functions with span_type for SequenceLabeling, category_type for DocumentClassification or relation_type. If you want to upload a config file use the functions post_span_type_upload, post_category_type_upload or post_relation_type_upload.
