### ISSUE TITLE
beta client 1.6+ compatibility

### ISSUE THREAD

**Issue by leonardlin** [doccano/doccano-client#72]
How to reproduce the behaviour
---------
I have forked the doccano-client and in my local environment made a few updates that it's compatible with 1.7.
Esp. project-attributes
span-types (ex labels)
relation-types (ex labels)

It would be easier to have a client that only needs to support 1.6+
or is the goal to have the beta client support 1.5+?

Does doccano-server support reporting back its own version, so that the client could feature toggle based on version?

I'm happy to merge back my local changes of the beta client to the repo

Your Environment
---------

*   Operating System:
*   Python Version:
*   Package Version:

**Comment by david-engelmann** [comment]
@leonardlin I believe once a PR addressing the broken type hint (Currently two are open) is merged the functions for the new label endpoints will work. I also included a fix on the post_members function. I find that If you want to know what endpoints you have access to, going to the YOUR_BASE_URL/swagger/ is super helpful. I'll do some investigating into pulling in that type of doccano version metadata but I haven't stumbled upon it yet.

**Comment by ljades** [comment]
Thank you so much for looking into this, was going to do some work on it myself but this saves time.

My hope is that, before making the beta client compatible with 1.6 (unless of course we make it backwards compatible with 1.5 as well), that the client gets at least one pypi version with 1.5 compatibility first. So I'd wait on that before overriding the 1.5 stuff (unless it's making it backwards compatible, as I said).

**Comment by ljades** [comment]
Hi @leonardlin, thanks again for your PR with the small beta client fixes! You mentioned you had made local changes to the client to be 1.7 compatible? Do you still have those/can you make a PR with them?
