### ISSUE TITLE
Publish New Version to PyPi with the Beta Client

### ISSUE THREAD

**Issue by ljades** [doccano/doccano-client#74]
Feature description
---------
Thanks for the prompt reviews on my code introducing the beta client code! Now, coinciding with https://github.com/doccano/doccano-client/issues/60 's steps forward, can we publish a new version to pypi with this code? Once we do, we can introduce new changes to get the beta client 1.6+ compatible.

**Comment by ljades** [comment]
@Hironsan are you the only one with publishing power? Also, is there a way I can be made a code contributor/reviewer for this package since I built out the new beta client? There's an outstanding PR with some fixes [here](https://github.com/doccano/doccano-client/pull/71) that I'd love to be able to help review.

**Comment by ljades** [comment]
It's actually probably best that this version of the package not get published until that #71 is merged.

**Comment by ljades** [comment]
Hey @afparsons and @Hironsan , sorry to bump and mention this again, but can we get an update on this? I'm actually going to be leaving my current company in the next three weeks, and I'd love to get an answer for if we can get contribution power or granting it to my coworker, @houssam7737. It'd allow us to switch to and develop actively on this package from our own internal package. It'd also give us more person-power to review new PRs on this repository.

Thank you in advance! And if that's too much to ask let me know as well.

**Comment by Hironsan** [comment]
Hi @ljades 
Sorry for the late reply.

Should I add you (and @houssam7737 ) to [doccano-client team](https://github.com/orgs/doccano/teams/client) and grant permission to commit?

**Comment by houssam7737** [comment]
Hi @Hironsan , yes please that would be greatly appreciated. Thanks!

**Comment by ljades** [comment]
Yes, thank you in advance!

**Comment by Hironsan** [comment]
@houssam7737 @ljades I send you invitations. Please accept it.

**Comment by armandgurgu23** [comment]
@ljades Do you have an estimate on when the new Doccano version will be published to PyPI?

**Comment by ljades** [comment]
Hi @armandgurgu23 , unsure. I do not personally have publish credentials or even guidelines for doing that. That would still be a question for @Hironsan . That being said, I can at least suggest that until a new PyPi version is published, you can do an install directly from github and a git commit hash. Hope that helps!

**Comment by Hironsan** [comment]
Can you have permission to create a tag and release the code? If you have it, the package will be automatically published to PyPI by the following workflow:

- [pypi-publish.yml](https://github.com/doccano/doccano-client/blob/master/.github/workflows/pypi-publish.yml)

Oh, but before releasing it, we need to fix the package version.

https://github.com/doccano/doccano-client/blob/fe125f409138d319fb1c74a0d3c41225c539e7f8/setup.py#L25
