### ISSUE TITLE
CI setup RFC

### ISSUE THREAD

**Issue by louisguitton** [doccano/doccano-client#9]
In [doccano-transformer](https://github.com/doccano/doccano-transformer), GitHub Actions are used to check to code conventions(flake8). I think if we add the action to this repository, it will be better. But this is another issue.

_Originally posted by @Hironsan in https://github.com/doccano/doccano-client/pull/7#issuecomment-639321819_

**Comment by louisguitton** [comment]
I'm proposing to add Github Actions with the following features:
- black formatting
- flake8 linting (including linting for annotations, docstrings and more) (see [here](https://github.com/louisguitton/simple-cookiecutter-python/blob/master/%7B%7Bcookiecutter.project%7D%7D/.pre-commit-config.yaml#L17-L26))
- import sorting
- generic pre-commit hooks (no trailing whitespaces etc...) (see [here](https://github.com/louisguitton/simple-cookiecutter-python/blob/master/%7B%7Bcookiecutter.project%7D%7D/.pre-commit-config.yaml#L40-L61))

See https://github.com/louisguitton/simple-cookiecutter-python for more details

This can be very quick, I can format the codebase as well. Once merged, the current opened PR can rebase on mine so that going forward with have one style.
I'm not going to open the PR if it stays stale, so just checking there is a real need for this.

cc: @Hironsan

**Comment by Hironsan** [comment]
Really good proposal. GitHub Actions is preferable.

**Comment by louisguitton** [comment]
PR ready for review @Hironsan
